import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'



export default function Home() {

  const [rate, setRated] = useState(6);
  const [isRated, setIsRated] = useState(false);

  const stars = [1,2,3,4,5];

  return (
    <div className='flex justify-center items-center min-w-screen min-h-screen'>
      <Head>
        <title>interactive rating</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>


      <section className={` mx-6 modal w-96 h-96 rounded-3xl p-8   
       transition-all duration-700  ${isRated ? "flip-card" : "" }`}>
        
        <div className={`flex flex-col h-full w-full justify-between backface-hidden ${isRated ? "hidden" : "" }`}>
          <div className='w-10 h-10 rounded-full bg-dark-blue flex justify-center items-center'>
            <Image 
            src={"/icon-star.svg"} 
            width={15}
            height={15}
            alt={"star"}
            className=""/>
          </div>

          <div>
            <h1 className='text-white text-2xl md:text-3xl font-bold '>How did we do?</h1>
            <p className="mt-2 text-med-gray">Please let us know how we did with your support request. 
            All feedback is appreciated to help us improve our offering!</p>
            
          </div>

          <div className='flex flex-row justify-between w-full text-med-gray '>
          {stars.map( star => {
              return (
                <button onClick={ () => setRated(star)} className={`flex justify-center items-center score w-10 h-10 md:w-12 md:h-12 rounded-full 
                hover:text-white ${rate === star ? "bg-orange text-white" :  "bg-dark-blue hover:bg-med-gray"} transition-all duration-100`}>
              {star}
            </button>
              )
          })}
            
          </div>

          <button onClick={ () => setIsRated(true)} className='text-white w-full rounded-full 
          py-3 bg-orange hover:bg-white hover:text-orange transition-all duration-200'>SUBMIT</button>

        </div>


        <div className='flip-card backface-hidden w-full h-full justify-between flex flex-col items-center'>

        
            <Image
            src={"/illustration-thank-you.svg"}
            height={100}
            width={130}
            alt={"thank you"}
            />

            <p className='px-4 py-2 bg-dark-blue rounded-full text-xs md:text-md text-orange'>{`You selected ${rate} out of 5`}</p>
            
            <div className="flex flex-col items-center">
              <h1 className='text-white text-xl md:text-2xl font-bold mb-2'>Thank You!</h1>

              <p className='text-med-gray'>We appreciate you taking the time to give a rating.
                If you everd need more support, don't hesitate to get in touch!
              </p>
            </div>

        </div>
      </section>

    </div>
  )
}
